spring.application.name: API-gateway
server.port: 8090
#eureka config
eureka.client.service-url.defaultZone: http://localhost:8761/eureka
#JwtService
jwt.secretKey: sdfjkgnsdkjfbskfdsbkjbfsbiudjvfsdfgsfdsgfdsfvdzvbfsdf

spring:
  cloud:
    gateway:
      routes:
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/post/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
          filters:
            - StripPrefix=2


        - id: Connections-service
          uri: lb://CONNECTIONS-SERVICE
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

