services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - linkedin-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - linkedin-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      - zookeeper


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
      - zookeeper

  notification-db:
    image: postgres:15
    container_name: notification-db
    environment:
      POSTGRES_DB: LinkedInNotificationService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Root@123
    volumes:
      - notification_data:/var/lib/postgresql/data
    networks:
      - linkedin-network

  posts-db:
    image: postgres:15
    container_name: post-db
    environment:
      POSTGRES_DB: LinkedInPostService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Root@123
    volumes:
      - post_data:/var/lib/postgresql/data
    networks:
      - linkedin-network

  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: LinkedInUserService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Root@123
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - linkedin-network

  connections-db:
    image: neo4j:5
    container_name: connections-db
    ports:
      - "7474:7474"   # Neo4j Browser (HTTP)
      - "7687:7687"   # Bolt protocol
    environment:
      NEO4J_AUTH: neo4j/Root@123
      NEO4J_dbms_default__database: linkedindb
    volumes:
      - connections_data:/data
    networks:
      - linkedin-network

  discovery-service:
    image: rohanpokale/linked-in/discovery-service:0.0.1
    container_name: discovery-service
    networks:
      - linkedin-network
    ports:
      - "8761:8761"

  post-service:
    image: rohanpokale/linked-in/post-service:0.0.1
    container_name: post-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-service
      - posts-db
      - kafka

  user-service:
    image: rohanpokale/linked-in/user-service:0.0.1
    container_name: user-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-service
      - user-db
      - kafka

  notification-service:
    image: rohanpokale/linked-in/notification-service:0.0.1
    container_name: notification-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-service
      - notification-db
      - kafka

  connections-service:
    image: rohanpokale/linked-in/connections-service:0.0.1
    container_name: connections-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-service
      - connections-db
      - kafka

  api-gateway:
    image: rohanpokale/linked-in/api-gateway:0.0.1
    container_name: api-gateway
    ports:
      - "8090:8090"
    networks:
      - linkedin-network
    depends_on:
      - discovery-service

volumes:
  notification_data:
  kafka_data:
  post_data:
  user_data:
  connections_data:

networks:
  linkedin-network:

#version: "3.8"
#
#services:
#  kafka:
#    image: docker.io/bitnami/kafka:latest
#    container_name: kafka
#    volumes:
#      - kafka_data:/bitnami
#    networks:
#      - linkedin-network
#    environment:
#      # KRaft settings
#      - KAFKA_CFG_NODE_ID=0
#      - KAFKA_CFG_PROCESS_ROLES=controller,broker
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
#      # Listeners
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
#
#  notification-db:
#    image: postgres
#    container_name: notification-db
#    environment:
#      POSTGRES_DB: LinkedInNotificationService
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: Root@123
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - linkedin-network
#
#  discovery-service:
#    image: rohanpokale/linked-in/discovery-service:0.0.1
#    container_name: discovery-service
#    networks:
#      - linkedin-network
#    ports:
#      - "8761:8761"
#
#  Notification-service:
#    image: rohanpokale/linked-in/notification-service:0.0.1
#    container_name: notification-service
#    networks:
#      - linkedin-network
#    depends_on:
#      - discovery-service
#      - notification-db
#      - kafka
#
#
#volumes:
#  kafka_data:
#  postgres_data:
#
#
#networks:
#  linkedin-network:
#
#
